plugins { id 'com.android.application' }
android {
  namespace 'ru.taishan.localization'
  compileSdk 35
  defaultConfig {
    applicationId 'ru.taishan.localization'
    minSdk 29
    targetSdk 31
    versionCode 9
    versionName '0.4.0'
  }
  lint {
    disable 'ExpiredTargetSdkVersion'
  }
  buildTypes {
    release {
      minifyEnabled false
      signingConfig signingConfigs.debug
    }
  }
}
